{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Experiment tracking\n",
    "\n",
    "This notebook is dedicated to show how experiment tracking works with MLflow in our case. Start by loading the train function.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append('../')\n",
    "\n",
    "from pathlib import Path\n",
    "from train_pipeline import experiment_tracking_train\n",
    "from model import network_definition_GCN_single_output\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Run an experiment:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Entering training loop\n",
      "Loading problem with 1087 variables and 13772 clauses\n",
      "Round 1 ending with 344 violated clauses\n",
      "Round 2 ending with 391 violated clauses\n",
      "Loading problem with 459 variables and 7054 clauses\n",
      "Round 1 ending with 91 violated clauses\n",
      "Round 2 ending with 81 violated clauses\n",
      "Loading problem with 6325 variables and 131973 clauses\n",
      "Round 1 ending with 16863 violated clauses\n",
      "Round 2 ending with 16737 violated clauses\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-21 15:00:45.802307: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] Constant folding an instruction is taking > 1s:\n",
      "\n",
      "  slice.61 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).\n",
      "\n",
      "This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.\n",
      "\n",
      "If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.\n",
      "2023-02-21 15:00:45.893776: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:133] The operation took 1.092182s\n",
      "Constant folding an instruction is taking > 1s:\n",
      "\n",
      "  slice.61 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).\n",
      "\n",
      "This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.\n",
      "\n",
      "If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/_5/jp84zrhn28sg9yqq0sq0dkfr0000gp/T/ipykernel_67569/3066289456.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;31m# EXPERIMENT_NAME = \"mlflow-random_3SAT-medium-GCN-LCG\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m experiment_tracking_train(\n\u001b[0m\u001b[1;32m     17\u001b[0m         \u001b[0mMODEL_REGISTRY\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m         \u001b[0mEXPERIMENT_NAME\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/python/src/train_pipeline.py\u001b[0m in \u001b[0;36mexperiment_tracking_train\u001b[0;34m(MODEL_REGISTRY, EXPERIMENT_NAME, batch_size, f, NUM_EPOCHS, N_STEPS_MOSER, N_RUNS_MOSER, path, img_path, model_path, network_definition, mode)\u001b[0m\n\u001b[1;32m    400\u001b[0m         )\n\u001b[1;32m    401\u001b[0m         \u001b[0;31m# train and evaluate\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 402\u001b[0;31m         artifacts = train(\n\u001b[0m\u001b[1;32m    403\u001b[0m             \u001b[0mbatch_size\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    404\u001b[0m             \u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/python/src/train_pipeline.py\u001b[0m in \u001b[0;36mtrain\u001b[0;34m(batch_size, f, NUM_EPOCHS, N_STEPS_MOSER, N_RUNS_MOSER, path, img_path, model_path, experiment_tracking, network_definition, mode)\u001b[0m\n\u001b[1;32m    312\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mepoch\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mNUM_EPOCHS\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m         \u001b[0mstart_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 314\u001b[0;31m         \u001b[0;32mfor\u001b[0m \u001b[0mcounter\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch\u001b[0m \u001b[0;32min\u001b[0m \u001b[0menumerate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain_loader\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    315\u001b[0m             \u001b[0;31m# print(\"batch_number\", counter)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    316\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmode\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"LCG\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py\u001b[0m in \u001b[0;36m__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    626\u001b[0m                 \u001b[0;31m# TODO(https://github.com/pytorch/pytorch/issues/76750)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    627\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_reset\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# type: ignore[call-arg]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 628\u001b[0;31m             \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_next_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    629\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_num_yielded\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    630\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_dataset_kind\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0m_DatasetKind\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mIterable\u001b[0m \u001b[0;32mand\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py\u001b[0m in \u001b[0;36m_next_data\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    669\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_next_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    670\u001b[0m         \u001b[0mindex\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_next_index\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# may raise StopIteration\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 671\u001b[0;31m         \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_dataset_fetcher\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfetch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mindex\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# may raise StopIteration\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    672\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_pin_memory\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    673\u001b[0m             \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_utils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpin_memory\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpin_memory\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_pin_memory_device\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\u001b[0m in \u001b[0;36mfetch\u001b[0;34m(self, possibly_batched_index)\u001b[0m\n\u001b[1;32m     56\u001b[0m                 \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__getitems__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m                 \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0midx\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0midx\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     59\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     60\u001b[0m             \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m     56\u001b[0m                 \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__getitems__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m                 \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0midx\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0midx\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     59\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     60\u001b[0m             \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mpossibly_batched_index\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataset.py\u001b[0m in \u001b[0;36m__getitem__\u001b[0;34m(self, idx)\u001b[0m\n\u001b[1;32m    293\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0midx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    294\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindices\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mi\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[0;32min\u001b[0m \u001b[0midx\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 295\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindices\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0midx\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    296\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    297\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__len__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/python/src/data_utils.py\u001b[0m in \u001b[0;36m__getitem__\u001b[0;34m(self, idx)\u001b[0m\n\u001b[1;32m    175\u001b[0m                 \u001b[0mpad_width\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mN\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mn\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    176\u001b[0m             )\n\u001b[0;32m--> 177\u001b[0;31m             energies = vmap(\n\u001b[0m\u001b[1;32m    178\u001b[0m                 \u001b[0mnumber_of_violated_constraints\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0min_axes\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mout_axes\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    179\u001b[0m             )(problem, candidates)\n",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/api.py\u001b[0m in \u001b[0;36mvmap_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m   1680\u001b[0m     axis_size_ = (axis_size if axis_size is not None else\n\u001b[1;32m   1681\u001b[0m                   _mapped_axis_size(fun, in_tree, args_flat, in_axes_flat, \"vmap\"))\n\u001b[0;32m-> 1682\u001b[0;31m     out_flat = batching.batch(\n\u001b[0m\u001b[1;32m   1683\u001b[0m         \u001b[0mflat_fun\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxis_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxis_size_\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0min_axes_flat\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1684\u001b[0m         \u001b[0;32mlambda\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mflatten_axes\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"vmap out_axes\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mout_tree\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mout_axes\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/linear_util.py\u001b[0m in \u001b[0;36mcall_wrapped\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    165\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    166\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 167\u001b[0;31m       \u001b[0mans\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mdict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    168\u001b[0m     \u001b[0;32mexcept\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    169\u001b[0m       \u001b[0;31m# Some transformations yield from inside context managers, so we have to\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/python/src/random_walk.py\u001b[0m in \u001b[0;36mnumber_of_violated_constraints\u001b[0;34m(problem, assignment)\u001b[0m\n\u001b[1;32m    102\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    103\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mnumber_of_violated_constraints\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mproblem\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mSATProblem\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0massignment\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 104\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mviolated_constraints\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mproblem\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0massignment\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mastype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mint\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    105\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    106\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/api.py\u001b[0m in \u001b[0;36mcache_miss\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    624\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    625\u001b[0m       out_flat = call_bind_continuation(\n\u001b[0;32m--> 626\u001b[0;31m           top_trace.process_call(primitive, fun_, tracers, params))\n\u001b[0m\u001b[1;32m    627\u001b[0m     \u001b[0mout_pytree_def\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mout_tree\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    628\u001b[0m     \u001b[0mout\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtree_unflatten\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mout_pytree_def\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mout_flat\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/interpreters/batching.py\u001b[0m in \u001b[0;36mprocess_call\u001b[0;34m(self, call_primitive, f, tracers, params)\u001b[0m\n\u001b[1;32m    375\u001b[0m     f_ = _update_annotation(f_, f.in_type, axis_size, self.axis_name, dims,\n\u001b[1;32m    376\u001b[0m                             segment_lens)\n\u001b[0;32m--> 377\u001b[0;31m     \u001b[0mvals_out\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcall_primitive\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbind\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf_\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0msegment_lens\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0mvals\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    378\u001b[0m     \u001b[0mvals_out\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdims_out\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mreassemble_concat_axes\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvals_out\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdims_out\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    379\u001b[0m     \u001b[0msrc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msource_info_util\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcurrent\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/core.py\u001b[0m in \u001b[0;36mbind\u001b[0;34m(self, fun, *args, **params)\u001b[0m\n\u001b[1;32m   2017\u001b[0m     call_bind_continuation, top_trace, fun_, tracers, params = (\n\u001b[1;32m   2018\u001b[0m         call_bind_with_continuation(self, fun, *args, **params))\n\u001b[0;32m-> 2019\u001b[0;31m     \u001b[0mouts\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtop_trace\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfun_\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtracers\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2020\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mcall_bind_continuation\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mouts\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2021\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/core.py\u001b[0m in \u001b[0;36mprocess_call\u001b[0;34m(self, primitive, f, tracers, params)\u001b[0m\n\u001b[1;32m    713\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    714\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mprocess_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprimitive\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtracers\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 715\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mprimitive\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mimpl\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0mtracers\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    716\u001b[0m   \u001b[0mprocess_map\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mprocess_call\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    717\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36m_xla_call_impl\u001b[0;34m(fun, device, backend, name, donated_invars, inline, keep_unused, *args)\u001b[0m\n\u001b[1;32m    240\u001b[0m def _xla_call_impl(fun: lu.WrappedFun, *args, device, backend, name,\n\u001b[1;32m    241\u001b[0m                    donated_invars, inline, keep_unused: bool):\n\u001b[0;32m--> 242\u001b[0;31m   compiled_fun = _xla_call_impl_lazy(\n\u001b[0m\u001b[1;32m    243\u001b[0m       \u001b[0mfun\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    244\u001b[0m       \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36m_xla_call_impl_lazy\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    234\u001b[0m       \u001b[0;32mraise\u001b[0m \u001b[0mNotImplementedError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Dynamic shapes do not work with Array.'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    235\u001b[0m     \u001b[0marg_specs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'_device'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mx\u001b[0m \u001b[0;32min\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 236\u001b[0;31m   return xla_callable(fun, device, backend, name, donated_invars, keep_unused,\n\u001b[0m\u001b[1;32m    237\u001b[0m                       *arg_specs)\n\u001b[1;32m    238\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/linear_util.py\u001b[0m in \u001b[0;36mmemoized_fun\u001b[0;34m(fun, *args)\u001b[0m\n\u001b[1;32m    301\u001b[0m       \u001b[0mfun\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpopulate_stores\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstores\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    302\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 303\u001b[0;31m       \u001b[0mans\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcall\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfun\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    304\u001b[0m       \u001b[0mcache\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mans\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfun\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstores\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    305\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36m_xla_callable_uncached\u001b[0;34m(fun, device, backend, name, donated_invars, keep_unused, *arg_specs)\u001b[0m\n\u001b[1;32m    357\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mcomputation\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_allow_propagation_to_outputs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munsafe_call\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    358\u001b[0m   \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 359\u001b[0;31m     return lower_xla_callable(fun, device, backend, name, donated_invars, False,\n\u001b[0m\u001b[1;32m    360\u001b[0m                               keep_unused, *arg_specs).compile().unsafe_call\n\u001b[1;32m    361\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36mcompile\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    994\u001b[0m       \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    995\u001b[0m         \u001b[0;32massert\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_out_type\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 996\u001b[0;31m         self._executable = XlaCompiledComputation.from_xla_computation(\n\u001b[0m\u001b[1;32m    997\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_hlo\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_in_type\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_out_type\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    998\u001b[0m             **self.compile_args)\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36mfrom_xla_computation\u001b[0;34m(name, xla_computation, in_type, out_type, nreps, device, backend, tuple_args, in_avals, out_avals, has_unordered_effects, ordered_effects, kept_var_idx, keepalive, host_callbacks)\u001b[0m\n\u001b[1;32m   1192\u001b[0m     with log_elapsed_time(f\"Finished XLA compilation of {name} \"\n\u001b[1;32m   1193\u001b[0m                           \"in {elapsed_time} sec\"):\n\u001b[0;32m-> 1194\u001b[0;31m       compiled = compile_or_get_cached(backend, xla_computation, options,\n\u001b[0m\u001b[1;32m   1195\u001b[0m                                        host_callbacks)\n\u001b[1;32m   1196\u001b[0m     buffer_counts = get_buffer_counts(out_avals, ordered_effects,\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36mcompile_or_get_cached\u001b[0;34m(backend, computation, compile_options, host_callbacks)\u001b[0m\n\u001b[1;32m   1075\u001b[0m       \u001b[0;32mreturn\u001b[0m \u001b[0mcompiled\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1076\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1077\u001b[0;31m   return backend_compile(backend, serialized_computation, compile_options,\n\u001b[0m\u001b[1;32m   1078\u001b[0m                          host_callbacks)\n\u001b[1;32m   1079\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/profiler.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    312\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mTraceAnnotation\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mdecorator_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 314\u001b[0;31m       \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    315\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    316\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/Applications/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py\u001b[0m in \u001b[0;36mbackend_compile\u001b[0;34m(backend, built_c, options, host_callbacks)\u001b[0m\n\u001b[1;32m   1010\u001b[0m   \u001b[0;31m# TODO(sharadmv): remove this fallback when all backends allow `compile`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1011\u001b[0m   \u001b[0;31m# to take in `host_callbacks`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1012\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mbackend\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbuilt_c\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompile_options\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0moptions\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1013\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1014\u001b[0m \u001b[0;31m# TODO(phawkins): update users.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2023-02-21 18:06:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:67692)\n",
      "[2023-02-21 18:06:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:67693)\n",
      "[2023-02-21 18:06:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:67694)\n",
      "[2023-02-21 18:06:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:67695)\n",
      "[2023-02-21 18:06:21 +0100] [67693] [INFO] Worker exiting (pid: 67693)\n",
      "[2023-02-21 18:06:21 +0100] [67692] [INFO] Worker exiting (pid: 67692)\n",
      "[2023-02-21 18:06:21 +0100] [67695] [INFO] Worker exiting (pid: 67695)\n",
      "[2023-02-21 18:06:21 +0100] [67694] [INFO] Worker exiting (pid: 67694)\n",
      "[2023-02-21 18:06:22 +0100] [67691] [WARNING] Worker with pid 67694 was terminated due to signal 9\n",
      "[2023-02-21 18:06:22 +0100] [67691] [WARNING] Worker with pid 67693 was terminated due to signal 9\n",
      "[2023-02-21 18:06:22 +0100] [67691] [WARNING] Worker with pid 67695 was terminated due to signal 9\n",
      "[2023-02-21 18:06:22 +0100] [67691] [WARNING] Worker with pid 67692 was terminated due to signal 9\n",
      "[2023-02-21 18:06:22 +0100] [73369] [INFO] Booting worker with pid: 73369\n",
      "[2023-02-21 18:06:22 +0100] [73370] [INFO] Booting worker with pid: 73370\n",
      "[2023-02-21 18:06:22 +0100] [73371] [INFO] Booting worker with pid: 73371\n",
      "[2023-02-21 18:06:22 +0100] [73375] [INFO] Booting worker with pid: 73375\n",
      "[2023-02-21 19:12:32 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73369)\n",
      "[2023-02-21 19:12:32 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73370)\n",
      "[2023-02-21 19:12:32 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73371)\n",
      "[2023-02-21 19:12:32 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73375)\n",
      "[2023-02-21 19:12:32 +0100] [73371] [INFO] Worker exiting (pid: 73371)\n",
      "[2023-02-21 19:12:32 +0100] [73369] [INFO] Worker exiting (pid: 73369)\n",
      "[2023-02-21 19:12:32 +0100] [73375] [INFO] Worker exiting (pid: 73375)\n",
      "[2023-02-21 19:12:32 +0100] [73370] [INFO] Worker exiting (pid: 73370)\n",
      "[2023-02-21 19:12:32 +0100] [67691] [WARNING] Worker with pid 73371 was terminated due to signal 9\n",
      "[2023-02-21 19:12:32 +0100] [67691] [WARNING] Worker with pid 73369 was terminated due to signal 9\n",
      "[2023-02-21 19:12:33 +0100] [73399] [INFO] Booting worker with pid: 73399\n",
      "[2023-02-21 19:12:33 +0100] [73400] [INFO] Booting worker with pid: 73400\n",
      "[2023-02-21 19:12:33 +0100] [73401] [INFO] Booting worker with pid: 73401\n",
      "[2023-02-21 19:12:33 +0100] [73403] [INFO] Booting worker with pid: 73403\n",
      "[2023-02-21 19:34:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73399)\n",
      "[2023-02-21 19:34:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73400)\n",
      "[2023-02-21 19:34:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73401)\n",
      "[2023-02-21 19:34:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73403)\n",
      "[2023-02-21 19:34:45 +0100] [73403] [INFO] Worker exiting (pid: 73403)\n",
      "[2023-02-21 19:34:45 +0100] [73400] [INFO] Worker exiting (pid: 73400)\n",
      "[2023-02-21 19:34:45 +0100] [73401] [INFO] Worker exiting (pid: 73401)\n",
      "[2023-02-21 19:34:45 +0100] [73399] [INFO] Worker exiting (pid: 73399)\n",
      "[2023-02-21 19:34:46 +0100] [67691] [WARNING] Worker with pid 73403 was terminated due to signal 9\n",
      "[2023-02-21 19:34:46 +0100] [67691] [WARNING] Worker with pid 73400 was terminated due to signal 9\n",
      "[2023-02-21 19:34:46 +0100] [67691] [WARNING] Worker with pid 73401 was terminated due to signal 9\n",
      "[2023-02-21 19:34:46 +0100] [67691] [WARNING] Worker with pid 73399 was terminated due to signal 9\n",
      "[2023-02-21 19:34:46 +0100] [73439] [INFO] Booting worker with pid: 73439\n",
      "[2023-02-21 19:34:46 +0100] [73440] [INFO] Booting worker with pid: 73440\n",
      "[2023-02-21 19:34:46 +0100] [73441] [INFO] Booting worker with pid: 73441\n",
      "[2023-02-21 19:34:46 +0100] [73442] [INFO] Booting worker with pid: 73442\n",
      "[2023-02-21 22:20:02 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73439)\n",
      "[2023-02-21 22:20:02 +0100] [73439] [INFO] Worker exiting (pid: 73439)\n",
      "[2023-02-21 22:20:03 +0100] [76919] [INFO] Booting worker with pid: 76919\n",
      "[2023-02-21 22:53:04 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73440)\n",
      "[2023-02-21 22:53:04 +0100] [73440] [INFO] Worker exiting (pid: 73440)\n",
      "[2023-02-21 22:53:06 +0100] [76950] [INFO] Booting worker with pid: 76950\n",
      "[2023-02-22 00:53:56 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73441)\n",
      "[2023-02-22 00:53:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:73442)\n",
      "[2023-02-22 00:53:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76919)\n",
      "[2023-02-22 00:53:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76950)\n",
      "[2023-02-22 00:53:57 +0100] [76950] [INFO] Worker exiting (pid: 76950)\n",
      "[2023-02-22 00:53:57 +0100] [73441] [INFO] Worker exiting (pid: 73441)\n",
      "[2023-02-22 00:53:57 +0100] [76919] [INFO] Worker exiting (pid: 76919)\n",
      "[2023-02-22 00:53:57 +0100] [73442] [INFO] Worker exiting (pid: 73442)\n",
      "[2023-02-22 00:53:58 +0100] [67691] [WARNING] Worker with pid 73442 was terminated due to signal 9\n",
      "[2023-02-22 00:53:58 +0100] [67691] [WARNING] Worker with pid 73441 was terminated due to signal 9\n",
      "[2023-02-22 00:53:58 +0100] [67691] [WARNING] Worker with pid 76919 was terminated due to signal 9\n",
      "[2023-02-22 00:53:58 +0100] [67691] [WARNING] Worker with pid 76950 was terminated due to signal 9\n",
      "[2023-02-22 00:53:58 +0100] [76974] [INFO] Booting worker with pid: 76974\n",
      "[2023-02-22 00:53:58 +0100] [76975] [INFO] Booting worker with pid: 76975\n",
      "[2023-02-22 00:53:58 +0100] [76976] [INFO] Booting worker with pid: 76976\n",
      "[2023-02-22 00:53:58 +0100] [76978] [INFO] Booting worker with pid: 76978\n",
      "[2023-02-22 02:12:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76974)\n",
      "[2023-02-22 02:12:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76975)\n",
      "[2023-02-22 02:12:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76976)\n",
      "[2023-02-22 02:12:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:76978)\n",
      "[2023-02-22 02:12:58 +0100] [76975] [INFO] Worker exiting (pid: 76975)\n",
      "[2023-02-22 02:12:58 +0100] [76978] [INFO] Worker exiting (pid: 76978)\n",
      "[2023-02-22 02:12:58 +0100] [76974] [INFO] Worker exiting (pid: 76974)\n",
      "[2023-02-22 02:12:58 +0100] [76976] [INFO] Worker exiting (pid: 76976)\n",
      "[2023-02-22 02:12:58 +0100] [67691] [WARNING] Worker with pid 76974 was terminated due to signal 9\n",
      "[2023-02-22 02:12:58 +0100] [67691] [WARNING] Worker with pid 76976 was terminated due to signal 9\n",
      "[2023-02-22 02:12:58 +0100] [67691] [WARNING] Worker with pid 76975 was terminated due to signal 9\n",
      "[2023-02-22 02:12:58 +0100] [67691] [WARNING] Worker with pid 76978 was terminated due to signal 9\n",
      "[2023-02-22 02:12:58 +0100] [77003] [INFO] Booting worker with pid: 77003\n",
      "[2023-02-22 02:12:58 +0100] [77004] [INFO] Booting worker with pid: 77004\n",
      "[2023-02-22 02:12:59 +0100] [77005] [INFO] Booting worker with pid: 77005\n",
      "[2023-02-22 02:12:59 +0100] [77006] [INFO] Booting worker with pid: 77006\n",
      "[2023-02-22 05:21:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77003)\n",
      "[2023-02-22 05:21:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77004)\n",
      "[2023-02-22 05:21:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77005)\n",
      "[2023-02-22 05:21:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77006)\n",
      "[2023-02-22 05:21:16 +0100] [77003] [INFO] Worker exiting (pid: 77003)\n",
      "[2023-02-22 05:21:16 +0100] [77006] [INFO] Worker exiting (pid: 77006)\n",
      "[2023-02-22 05:21:16 +0100] [77004] [INFO] Worker exiting (pid: 77004)\n",
      "[2023-02-22 05:21:16 +0100] [77005] [INFO] Worker exiting (pid: 77005)\n",
      "[2023-02-22 05:21:17 +0100] [67691] [WARNING] Worker with pid 77006 was terminated due to signal 9\n",
      "[2023-02-22 05:21:17 +0100] [67691] [WARNING] Worker with pid 77005 was terminated due to signal 9\n",
      "[2023-02-22 05:21:17 +0100] [67691] [WARNING] Worker with pid 77004 was terminated due to signal 9\n",
      "[2023-02-22 05:21:17 +0100] [67691] [WARNING] Worker with pid 77003 was terminated due to signal 9\n",
      "[2023-02-22 05:21:17 +0100] [77055] [INFO] Booting worker with pid: 77055\n",
      "[2023-02-22 05:21:17 +0100] [77056] [INFO] Booting worker with pid: 77056\n",
      "[2023-02-22 05:21:17 +0100] [77057] [INFO] Booting worker with pid: 77057\n",
      "[2023-02-22 05:21:17 +0100] [77058] [INFO] Booting worker with pid: 77058\n",
      "[2023-02-22 06:46:04 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77055)\n",
      "[2023-02-22 06:46:04 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77056)\n",
      "[2023-02-22 06:46:04 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77057)\n",
      "[2023-02-22 06:46:04 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77058)\n",
      "[2023-02-22 06:46:04 +0100] [77057] [INFO] Worker exiting (pid: 77057)\n",
      "[2023-02-22 06:46:04 +0100] [77058] [INFO] Worker exiting (pid: 77058)\n",
      "[2023-02-22 06:46:04 +0100] [77055] [INFO] Worker exiting (pid: 77055)\n",
      "[2023-02-22 06:46:04 +0100] [77056] [INFO] Worker exiting (pid: 77056)\n",
      "[2023-02-22 06:46:05 +0100] [77079] [INFO] Booting worker with pid: 77079\n",
      "[2023-02-22 06:46:05 +0100] [67691] [WARNING] Worker with pid 77056 was terminated due to signal 9\n",
      "[2023-02-22 06:46:05 +0100] [77080] [INFO] Booting worker with pid: 77080\n",
      "[2023-02-22 06:46:05 +0100] [77081] [INFO] Booting worker with pid: 77081\n",
      "[2023-02-22 06:46:05 +0100] [77082] [INFO] Booting worker with pid: 77082\n",
      "[2023-02-22 07:06:06 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77079)\n",
      "[2023-02-22 07:06:06 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77080)\n",
      "[2023-02-22 07:06:06 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77081)\n",
      "[2023-02-22 07:06:06 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77082)\n",
      "[2023-02-22 07:06:06 +0100] [77080] [INFO] Worker exiting (pid: 77080)\n",
      "[2023-02-22 07:06:06 +0100] [77079] [INFO] Worker exiting (pid: 77079)\n",
      "[2023-02-22 07:06:06 +0100] [77082] [INFO] Worker exiting (pid: 77082)\n",
      "[2023-02-22 07:06:06 +0100] [77081] [INFO] Worker exiting (pid: 77081)\n",
      "[2023-02-22 07:06:07 +0100] [77228] [INFO] Booting worker with pid: 77228\n",
      "[2023-02-22 07:06:07 +0100] [77229] [INFO] Booting worker with pid: 77229\n",
      "[2023-02-22 07:06:07 +0100] [77230] [INFO] Booting worker with pid: 77230\n",
      "[2023-02-22 07:06:07 +0100] [77231] [INFO] Booting worker with pid: 77231\n",
      "[2023-02-22 08:00:01 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77228)\n",
      "[2023-02-22 08:00:01 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77229)\n",
      "[2023-02-22 08:00:01 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77230)\n",
      "[2023-02-22 08:00:01 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77231)\n",
      "[2023-02-22 08:00:01 +0100] [77230] [INFO] Worker exiting (pid: 77230)\n",
      "[2023-02-22 08:00:01 +0100] [77228] [INFO] Worker exiting (pid: 77228)\n",
      "[2023-02-22 08:00:01 +0100] [77229] [INFO] Worker exiting (pid: 77229)\n",
      "[2023-02-22 08:00:01 +0100] [77231] [INFO] Worker exiting (pid: 77231)\n",
      "[2023-02-22 08:00:01 +0100] [77305] [INFO] Booting worker with pid: 77305\n",
      "[2023-02-22 08:00:01 +0100] [77306] [INFO] Booting worker with pid: 77306\n",
      "[2023-02-22 08:00:01 +0100] [77307] [INFO] Booting worker with pid: 77307\n",
      "[2023-02-22 08:00:02 +0100] [77309] [INFO] Booting worker with pid: 77309\n",
      "[2023-02-22 08:21:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77305)\n",
      "[2023-02-22 08:21:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77306)\n",
      "[2023-02-22 08:21:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77307)\n",
      "[2023-02-22 08:21:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77309)\n",
      "[2023-02-22 08:21:13 +0100] [77306] [INFO] Worker exiting (pid: 77306)\n",
      "[2023-02-22 08:21:13 +0100] [77307] [INFO] Worker exiting (pid: 77307)\n",
      "[2023-02-22 08:21:13 +0100] [77309] [INFO] Worker exiting (pid: 77309)\n",
      "[2023-02-22 08:21:13 +0100] [77305] [INFO] Worker exiting (pid: 77305)\n",
      "[2023-02-22 08:21:13 +0100] [77512] [INFO] Booting worker with pid: 77512\n",
      "[2023-02-22 08:21:13 +0100] [77513] [INFO] Booting worker with pid: 77513\n",
      "[2023-02-22 08:21:13 +0100] [77514] [INFO] Booting worker with pid: 77514\n",
      "[2023-02-22 08:21:13 +0100] [77515] [INFO] Booting worker with pid: 77515\n",
      "[2023-02-22 11:38:43 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77512)\n",
      "[2023-02-22 11:38:43 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77513)\n",
      "[2023-02-22 11:38:43 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77514)\n",
      "[2023-02-22 11:38:43 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77515)\n",
      "[2023-02-22 11:38:43 +0100] [77514] [INFO] Worker exiting (pid: 77514)\n",
      "[2023-02-22 11:38:43 +0100] [77512] [INFO] Worker exiting (pid: 77512)\n",
      "[2023-02-22 11:38:43 +0100] [77513] [INFO] Worker exiting (pid: 77513)\n",
      "[2023-02-22 11:38:43 +0100] [77515] [INFO] Worker exiting (pid: 77515)\n",
      "[2023-02-22 11:38:43 +0100] [77618] [INFO] Booting worker with pid: 77618\n",
      "[2023-02-22 11:38:43 +0100] [77619] [INFO] Booting worker with pid: 77619\n",
      "[2023-02-22 11:38:43 +0100] [77620] [INFO] Booting worker with pid: 77620\n",
      "[2023-02-22 11:38:43 +0100] [77621] [INFO] Booting worker with pid: 77621\n",
      "[2023-02-22 13:14:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77618)\n",
      "[2023-02-22 13:14:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77619)\n",
      "[2023-02-22 13:14:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77620)\n",
      "[2023-02-22 13:14:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77621)\n",
      "[2023-02-22 13:14:26 +0100] [77618] [INFO] Worker exiting (pid: 77618)\n",
      "[2023-02-22 13:14:26 +0100] [77621] [INFO] Worker exiting (pid: 77621)\n",
      "[2023-02-22 13:14:26 +0100] [77620] [INFO] Worker exiting (pid: 77620)\n",
      "[2023-02-22 13:14:26 +0100] [77619] [INFO] Worker exiting (pid: 77619)\n",
      "[2023-02-22 13:14:26 +0100] [77942] [INFO] Booting worker with pid: 77942\n",
      "[2023-02-22 13:14:26 +0100] [77938] [INFO] Booting worker with pid: 77938\n",
      "[2023-02-22 13:14:26 +0100] [77943] [INFO] Booting worker with pid: 77943\n",
      "[2023-02-22 13:14:26 +0100] [77944] [INFO] Booting worker with pid: 77944\n",
      "[2023-02-22 14:24:00 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77938)\n",
      "[2023-02-22 14:24:00 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77942)\n",
      "[2023-02-22 14:24:00 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77943)\n",
      "[2023-02-22 14:24:00 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:77944)\n",
      "[2023-02-22 14:24:00 +0100] [77943] [INFO] Worker exiting (pid: 77943)\n",
      "[2023-02-22 14:24:00 +0100] [77938] [INFO] Worker exiting (pid: 77938)\n",
      "[2023-02-22 14:24:00 +0100] [77942] [INFO] Worker exiting (pid: 77942)\n",
      "[2023-02-22 14:24:00 +0100] [77944] [INFO] Worker exiting (pid: 77944)\n",
      "[2023-02-22 14:24:01 +0100] [67691] [WARNING] Worker with pid 77943 was terminated due to signal 9\n",
      "[2023-02-22 14:24:01 +0100] [67691] [WARNING] Worker with pid 77938 was terminated due to signal 9\n",
      "[2023-02-22 14:24:01 +0100] [67691] [WARNING] Worker with pid 77942 was terminated due to signal 9\n",
      "[2023-02-22 14:24:01 +0100] [67691] [WARNING] Worker with pid 77944 was terminated due to signal 9\n",
      "[2023-02-22 14:24:01 +0100] [93404] [INFO] Booting worker with pid: 93404\n",
      "[2023-02-22 14:24:01 +0100] [93405] [INFO] Booting worker with pid: 93405\n",
      "[2023-02-22 14:24:01 +0100] [93408] [INFO] Booting worker with pid: 93408\n",
      "[2023-02-22 14:24:01 +0100] [93409] [INFO] Booting worker with pid: 93409\n",
      "[2023-02-22 14:32:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93404)\n",
      "[2023-02-22 14:32:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93405)\n",
      "[2023-02-22 14:32:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93408)\n",
      "[2023-02-22 14:32:21 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93409)\n",
      "[2023-02-22 14:32:21 +0100] [93404] [INFO] Worker exiting (pid: 93404)\n",
      "[2023-02-22 14:32:21 +0100] [93409] [INFO] Worker exiting (pid: 93409)\n",
      "[2023-02-22 14:32:21 +0100] [93408] [INFO] Worker exiting (pid: 93408)\n",
      "[2023-02-22 14:32:21 +0100] [93405] [INFO] Worker exiting (pid: 93405)\n",
      "[2023-02-22 14:32:22 +0100] [93636] [INFO] Booting worker with pid: 93636\n",
      "[2023-02-22 14:32:22 +0100] [67691] [WARNING] Worker with pid 93404 was terminated due to signal 9\n",
      "[2023-02-22 14:32:22 +0100] [93637] [INFO] Booting worker with pid: 93637\n",
      "[2023-02-22 14:32:22 +0100] [93638] [INFO] Booting worker with pid: 93638\n",
      "[2023-02-22 14:32:22 +0100] [93639] [INFO] Booting worker with pid: 93639\n",
      "[2023-02-22 15:15:35 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93636)\n",
      "[2023-02-22 15:15:35 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93637)\n",
      "[2023-02-22 15:15:35 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93638)\n",
      "[2023-02-22 15:15:35 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:93639)\n",
      "[2023-02-22 15:15:35 +0100] [93639] [INFO] Worker exiting (pid: 93639)\n",
      "[2023-02-22 15:15:35 +0100] [93638] [INFO] Worker exiting (pid: 93638)\n",
      "[2023-02-22 15:15:35 +0100] [93637] [INFO] Worker exiting (pid: 93637)\n",
      "[2023-02-22 15:15:35 +0100] [93636] [INFO] Worker exiting (pid: 93636)\n",
      "[2023-02-22 15:15:36 +0100] [95665] [INFO] Booting worker with pid: 95665\n",
      "[2023-02-22 15:15:36 +0100] [95666] [INFO] Booting worker with pid: 95666\n",
      "[2023-02-22 15:15:36 +0100] [95667] [INFO] Booting worker with pid: 95667\n",
      "[2023-02-22 15:15:36 +0100] [95668] [INFO] Booting worker with pid: 95668\n",
      "[2023-02-22 15:19:07 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95665)\n",
      "[2023-02-22 15:19:07 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95666)\n",
      "[2023-02-22 15:19:07 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95667)\n",
      "[2023-02-22 15:19:07 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95668)\n",
      "[2023-02-22 15:19:07 +0100] [95665] [INFO] Worker exiting (pid: 95665)\n",
      "[2023-02-22 15:19:07 +0100] [95666] [INFO] Worker exiting (pid: 95666)\n",
      "[2023-02-22 15:19:07 +0100] [95667] [INFO] Worker exiting (pid: 95667)\n",
      "[2023-02-22 15:19:07 +0100] [95668] [INFO] Worker exiting (pid: 95668)\n",
      "[2023-02-22 15:19:07 +0100] [95685] [INFO] Booting worker with pid: 95685\n",
      "[2023-02-22 15:19:07 +0100] [95686] [INFO] Booting worker with pid: 95686\n",
      "[2023-02-22 15:19:08 +0100] [95687] [INFO] Booting worker with pid: 95687\n",
      "[2023-02-22 15:19:08 +0100] [95688] [INFO] Booting worker with pid: 95688\n",
      "[2023-02-22 15:20:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95685)\n",
      "[2023-02-22 15:20:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95686)\n",
      "[2023-02-22 15:20:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95687)\n",
      "[2023-02-22 15:20:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95688)\n",
      "[2023-02-22 15:20:22 +0100] [95688] [INFO] Worker exiting (pid: 95688)\n",
      "[2023-02-22 15:20:22 +0100] [95685] [INFO] Worker exiting (pid: 95685)\n",
      "[2023-02-22 15:20:22 +0100] [95686] [INFO] Worker exiting (pid: 95686)\n",
      "[2023-02-22 15:20:22 +0100] [95687] [INFO] Worker exiting (pid: 95687)\n",
      "[2023-02-22 15:20:22 +0100] [95707] [INFO] Booting worker with pid: 95707\n",
      "[2023-02-22 15:20:23 +0100] [95708] [INFO] Booting worker with pid: 95708\n",
      "[2023-02-22 15:20:23 +0100] [95709] [INFO] Booting worker with pid: 95709\n",
      "[2023-02-22 15:20:23 +0100] [95710] [INFO] Booting worker with pid: 95710\n",
      "[2023-02-22 15:42:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95707)\n",
      "[2023-02-22 15:42:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95708)\n",
      "[2023-02-22 15:42:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95709)\n",
      "[2023-02-22 15:42:26 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95710)\n",
      "[2023-02-22 15:42:26 +0100] [95708] [INFO] Worker exiting (pid: 95708)\n",
      "[2023-02-22 15:42:26 +0100] [95709] [INFO] Worker exiting (pid: 95709)\n",
      "[2023-02-22 15:42:26 +0100] [95710] [INFO] Worker exiting (pid: 95710)\n",
      "[2023-02-22 15:42:26 +0100] [95707] [INFO] Worker exiting (pid: 95707)\n",
      "[2023-02-22 15:42:27 +0100] [67691] [WARNING] Worker with pid 95710 was terminated due to signal 9\n",
      "[2023-02-22 15:42:27 +0100] [67691] [WARNING] Worker with pid 95708 was terminated due to signal 9\n",
      "[2023-02-22 15:42:27 +0100] [67691] [WARNING] Worker with pid 95707 was terminated due to signal 9\n",
      "[2023-02-22 15:42:27 +0100] [67691] [WARNING] Worker with pid 95709 was terminated due to signal 9\n",
      "[2023-02-22 15:42:27 +0100] [95740] [INFO] Booting worker with pid: 95740\n",
      "[2023-02-22 15:42:27 +0100] [95741] [INFO] Booting worker with pid: 95741\n",
      "[2023-02-22 15:42:27 +0100] [95742] [INFO] Booting worker with pid: 95742\n",
      "[2023-02-22 15:42:27 +0100] [95743] [INFO] Booting worker with pid: 95743\n",
      "[2023-02-22 17:07:56 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95740)\n",
      "[2023-02-22 17:07:56 +0100] [95740] [INFO] Worker exiting (pid: 95740)\n",
      "[2023-02-22 17:07:57 +0100] [67691] [WARNING] Worker with pid 95740 was terminated due to signal 9\n",
      "[2023-02-22 17:07:57 +0100] [96736] [INFO] Booting worker with pid: 96736\n",
      "[2023-02-22 18:00:50 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95741)\n",
      "[2023-02-22 18:00:50 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95742)\n",
      "[2023-02-22 18:00:50 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:95743)\n",
      "[2023-02-22 18:00:50 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:96736)\n",
      "[2023-02-22 18:00:50 +0100] [96736] [INFO] Worker exiting (pid: 96736)\n",
      "[2023-02-22 18:00:50 +0100] [95742] [INFO] Worker exiting (pid: 95742)\n",
      "[2023-02-22 18:00:50 +0100] [95743] [INFO] Worker exiting (pid: 95743)\n",
      "[2023-02-22 18:00:50 +0100] [95741] [INFO] Worker exiting (pid: 95741)\n",
      "[2023-02-22 18:00:51 +0100] [67691] [WARNING] Worker with pid 96736 was terminated due to signal 9\n",
      "[2023-02-22 18:00:51 +0100] [67691] [WARNING] Worker with pid 95741 was terminated due to signal 9\n",
      "[2023-02-22 18:00:51 +0100] [67691] [WARNING] Worker with pid 95742 was terminated due to signal 9\n",
      "[2023-02-22 18:00:51 +0100] [67691] [WARNING] Worker with pid 95743 was terminated due to signal 9\n",
      "[2023-02-22 18:00:51 +0100] [96996] [INFO] Booting worker with pid: 96996\n",
      "[2023-02-22 18:00:51 +0100] [96999] [INFO] Booting worker with pid: 96999\n",
      "[2023-02-22 18:00:51 +0100] [97002] [INFO] Booting worker with pid: 97002\n",
      "[2023-02-22 18:00:51 +0100] [97005] [INFO] Booting worker with pid: 97005\n",
      "[2023-02-22 19:41:36 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:96996)\n",
      "[2023-02-22 19:41:36 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:96999)\n",
      "[2023-02-22 19:41:36 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:97002)\n",
      "[2023-02-22 19:41:36 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:97005)\n",
      "[2023-02-22 19:41:36 +0100] [96999] [INFO] Worker exiting (pid: 96999)\n",
      "[2023-02-22 19:41:36 +0100] [97005] [INFO] Worker exiting (pid: 97005)\n",
      "[2023-02-22 19:41:36 +0100] [97002] [INFO] Worker exiting (pid: 97002)\n",
      "[2023-02-22 19:41:36 +0100] [96996] [INFO] Worker exiting (pid: 96996)\n",
      "[2023-02-22 19:41:37 +0100] [67691] [WARNING] Worker with pid 97005 was terminated due to signal 9\n",
      "[2023-02-22 19:41:37 +0100] [67691] [WARNING] Worker with pid 96996 was terminated due to signal 9\n",
      "[2023-02-22 19:41:37 +0100] [67691] [WARNING] Worker with pid 96999 was terminated due to signal 9\n",
      "[2023-02-22 19:41:37 +0100] [67691] [WARNING] Worker with pid 97002 was terminated due to signal 9\n",
      "[2023-02-22 19:41:37 +0100] [1882] [INFO] Booting worker with pid: 1882\n",
      "[2023-02-22 19:41:37 +0100] [1883] [INFO] Booting worker with pid: 1883\n",
      "[2023-02-22 19:41:37 +0100] [1884] [INFO] Booting worker with pid: 1884\n",
      "[2023-02-22 19:41:37 +0100] [1885] [INFO] Booting worker with pid: 1885\n",
      "[2023-02-22 19:51:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1882)\n",
      "[2023-02-22 19:51:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1883)\n",
      "[2023-02-22 19:51:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1884)\n",
      "[2023-02-22 19:51:45 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1885)\n",
      "[2023-02-22 19:51:45 +0100] [1883] [INFO] Worker exiting (pid: 1883)\n",
      "[2023-02-22 19:51:45 +0100] [1882] [INFO] Worker exiting (pid: 1882)\n",
      "[2023-02-22 19:51:45 +0100] [1884] [INFO] Worker exiting (pid: 1884)\n",
      "[2023-02-22 19:51:45 +0100] [1885] [INFO] Worker exiting (pid: 1885)\n",
      "[2023-02-22 19:51:46 +0100] [1973] [INFO] Booting worker with pid: 1973\n",
      "[2023-02-22 19:51:46 +0100] [1974] [INFO] Booting worker with pid: 1974\n",
      "[2023-02-22 19:51:46 +0100] [1975] [INFO] Booting worker with pid: 1975\n",
      "[2023-02-22 19:51:46 +0100] [1976] [INFO] Booting worker with pid: 1976\n",
      "[2023-02-22 20:17:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1973)\n",
      "[2023-02-22 20:17:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1974)\n",
      "[2023-02-22 20:17:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1975)\n",
      "[2023-02-22 20:17:22 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1976)\n",
      "[2023-02-22 20:17:22 +0100] [1976] [INFO] Worker exiting (pid: 1976)\n",
      "[2023-02-22 20:17:22 +0100] [1973] [INFO] Worker exiting (pid: 1973)\n",
      "[2023-02-22 20:17:22 +0100] [1975] [INFO] Worker exiting (pid: 1975)\n",
      "[2023-02-22 20:17:22 +0100] [1974] [INFO] Worker exiting (pid: 1974)\n",
      "[2023-02-22 20:17:23 +0100] [1994] [INFO] Booting worker with pid: 1994\n",
      "[2023-02-22 20:17:23 +0100] [1997] [INFO] Booting worker with pid: 1997\n",
      "[2023-02-22 20:17:23 +0100] [1998] [INFO] Booting worker with pid: 1998\n",
      "[2023-02-22 20:17:23 +0100] [1999] [INFO] Booting worker with pid: 1999\n",
      "[2023-02-22 21:34:12 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1994)\n",
      "[2023-02-22 21:34:12 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1997)\n",
      "[2023-02-22 21:34:12 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1998)\n",
      "[2023-02-22 21:34:12 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:1999)\n",
      "[2023-02-22 21:34:12 +0100] [1997] [INFO] Worker exiting (pid: 1997)\n",
      "[2023-02-22 21:34:12 +0100] [1994] [INFO] Worker exiting (pid: 1994)\n",
      "[2023-02-22 21:34:12 +0100] [1999] [INFO] Worker exiting (pid: 1999)\n",
      "[2023-02-22 21:34:12 +0100] [1998] [INFO] Worker exiting (pid: 1998)\n",
      "[2023-02-22 21:34:13 +0100] [67691] [WARNING] Worker with pid 1999 was terminated due to signal 9\n",
      "[2023-02-22 21:34:13 +0100] [67691] [WARNING] Worker with pid 1998 was terminated due to signal 9\n",
      "[2023-02-22 21:34:13 +0100] [67691] [WARNING] Worker with pid 1997 was terminated due to signal 9\n",
      "[2023-02-22 21:34:13 +0100] [67691] [WARNING] Worker with pid 1994 was terminated due to signal 9\n",
      "[2023-02-22 21:34:13 +0100] [2165] [INFO] Booting worker with pid: 2165\n",
      "[2023-02-22 21:34:13 +0100] [2167] [INFO] Booting worker with pid: 2167\n",
      "[2023-02-22 21:34:13 +0100] [2169] [INFO] Booting worker with pid: 2169\n",
      "[2023-02-22 21:34:13 +0100] [2170] [INFO] Booting worker with pid: 2170\n",
      "[2023-02-22 23:32:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2165)\n",
      "[2023-02-22 23:32:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2167)\n",
      "[2023-02-22 23:32:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2169)\n",
      "[2023-02-22 23:32:13 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2170)\n",
      "[2023-02-22 23:32:13 +0100] [2165] [INFO] Worker exiting (pid: 2165)\n",
      "[2023-02-22 23:32:13 +0100] [2169] [INFO] Worker exiting (pid: 2169)\n",
      "[2023-02-22 23:32:13 +0100] [2170] [INFO] Worker exiting (pid: 2170)\n",
      "[2023-02-22 23:32:13 +0100] [2167] [INFO] Worker exiting (pid: 2167)\n",
      "[2023-02-22 23:32:14 +0100] [67691] [WARNING] Worker with pid 2169 was terminated due to signal 9\n",
      "[2023-02-22 23:32:14 +0100] [67691] [WARNING] Worker with pid 2165 was terminated due to signal 9\n",
      "[2023-02-22 23:32:14 +0100] [67691] [WARNING] Worker with pid 2170 was terminated due to signal 9\n",
      "[2023-02-22 23:32:14 +0100] [67691] [WARNING] Worker with pid 2167 was terminated due to signal 9\n",
      "[2023-02-22 23:32:14 +0100] [2243] [INFO] Booting worker with pid: 2243\n",
      "[2023-02-22 23:32:14 +0100] [2244] [INFO] Booting worker with pid: 2244\n",
      "[2023-02-22 23:32:14 +0100] [2245] [INFO] Booting worker with pid: 2245\n",
      "[2023-02-22 23:32:14 +0100] [2246] [INFO] Booting worker with pid: 2246\n",
      "[2023-02-23 01:33:05 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2243)\n",
      "[2023-02-23 01:33:05 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2244)\n",
      "[2023-02-23 01:33:05 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2245)\n",
      "[2023-02-23 01:33:05 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2246)\n",
      "[2023-02-23 01:33:06 +0100] [2246] [INFO] Worker exiting (pid: 2246)\n",
      "[2023-02-23 01:33:06 +0100] [2244] [INFO] Worker exiting (pid: 2244)\n",
      "[2023-02-23 01:33:06 +0100] [2245] [INFO] Worker exiting (pid: 2245)\n",
      "[2023-02-23 01:33:06 +0100] [2243] [INFO] Worker exiting (pid: 2243)\n",
      "[2023-02-23 01:33:06 +0100] [67691] [WARNING] Worker with pid 2246 was terminated due to signal 9\n",
      "[2023-02-23 01:33:06 +0100] [67691] [WARNING] Worker with pid 2245 was terminated due to signal 9\n",
      "[2023-02-23 01:33:06 +0100] [67691] [WARNING] Worker with pid 2244 was terminated due to signal 9\n",
      "[2023-02-23 01:33:06 +0100] [67691] [WARNING] Worker with pid 2243 was terminated due to signal 9\n",
      "[2023-02-23 01:33:06 +0100] [2327] [INFO] Booting worker with pid: 2327\n",
      "[2023-02-23 01:33:06 +0100] [2328] [INFO] Booting worker with pid: 2328\n",
      "[2023-02-23 01:33:06 +0100] [2329] [INFO] Booting worker with pid: 2329\n",
      "[2023-02-23 01:33:06 +0100] [2330] [INFO] Booting worker with pid: 2330\n",
      "[2023-02-23 03:33:56 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2327)\n",
      "[2023-02-23 03:33:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2328)\n",
      "[2023-02-23 03:33:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2329)\n",
      "[2023-02-23 03:33:57 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2330)\n",
      "[2023-02-23 03:33:57 +0100] [2327] [INFO] Worker exiting (pid: 2327)\n",
      "[2023-02-23 03:33:57 +0100] [2329] [INFO] Worker exiting (pid: 2329)\n",
      "[2023-02-23 03:33:57 +0100] [2328] [INFO] Worker exiting (pid: 2328)\n",
      "[2023-02-23 03:33:57 +0100] [2330] [INFO] Worker exiting (pid: 2330)\n",
      "[2023-02-23 03:33:58 +0100] [67691] [WARNING] Worker with pid 2330 was terminated due to signal 9\n",
      "[2023-02-23 03:33:58 +0100] [67691] [WARNING] Worker with pid 2328 was terminated due to signal 9\n",
      "[2023-02-23 03:33:58 +0100] [67691] [WARNING] Worker with pid 2327 was terminated due to signal 9\n",
      "[2023-02-23 03:33:58 +0100] [67691] [WARNING] Worker with pid 2329 was terminated due to signal 9\n",
      "[2023-02-23 03:33:58 +0100] [2365] [INFO] Booting worker with pid: 2365\n",
      "[2023-02-23 03:33:58 +0100] [2367] [INFO] Booting worker with pid: 2367\n",
      "[2023-02-23 03:33:58 +0100] [2368] [INFO] Booting worker with pid: 2368\n",
      "[2023-02-23 03:33:58 +0100] [2369] [INFO] Booting worker with pid: 2369\n",
      "[2023-02-23 05:08:10 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2365)\n",
      "[2023-02-23 05:08:10 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2367)\n",
      "[2023-02-23 05:08:10 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2368)\n",
      "[2023-02-23 05:08:10 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2369)\n",
      "[2023-02-23 05:08:10 +0100] [2368] [INFO] Worker exiting (pid: 2368)\n",
      "[2023-02-23 05:08:10 +0100] [2365] [INFO] Worker exiting (pid: 2365)\n",
      "[2023-02-23 05:08:10 +0100] [2367] [INFO] Worker exiting (pid: 2367)\n",
      "[2023-02-23 05:08:10 +0100] [2369] [INFO] Worker exiting (pid: 2369)\n",
      "[2023-02-23 05:08:11 +0100] [67691] [WARNING] Worker with pid 2369 was terminated due to signal 9\n",
      "[2023-02-23 05:08:11 +0100] [67691] [WARNING] Worker with pid 2368 was terminated due to signal 9\n",
      "[2023-02-23 05:08:11 +0100] [67691] [WARNING] Worker with pid 2367 was terminated due to signal 9\n",
      "[2023-02-23 05:08:11 +0100] [67691] [WARNING] Worker with pid 2365 was terminated due to signal 9\n",
      "[2023-02-23 05:08:11 +0100] [2414] [INFO] Booting worker with pid: 2414\n",
      "[2023-02-23 05:08:11 +0100] [2415] [INFO] Booting worker with pid: 2415\n",
      "[2023-02-23 05:08:11 +0100] [2416] [INFO] Booting worker with pid: 2416\n",
      "[2023-02-23 05:08:11 +0100] [2417] [INFO] Booting worker with pid: 2417\n",
      "[2023-02-23 07:08:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2414)\n",
      "[2023-02-23 07:08:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2415)\n",
      "[2023-02-23 07:08:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2416)\n",
      "[2023-02-23 07:08:16 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2417)\n",
      "[2023-02-23 07:08:17 +0100] [2416] [INFO] Worker exiting (pid: 2416)\n",
      "[2023-02-23 07:08:17 +0100] [2417] [INFO] Worker exiting (pid: 2417)\n",
      "[2023-02-23 07:08:17 +0100] [2414] [INFO] Worker exiting (pid: 2414)\n",
      "[2023-02-23 07:08:17 +0100] [2415] [INFO] Worker exiting (pid: 2415)\n",
      "[2023-02-23 07:08:17 +0100] [2429] [INFO] Booting worker with pid: 2429\n",
      "[2023-02-23 07:08:17 +0100] [2430] [INFO] Booting worker with pid: 2430\n",
      "[2023-02-23 07:08:17 +0100] [2431] [INFO] Booting worker with pid: 2431\n",
      "[2023-02-23 07:08:17 +0100] [2432] [INFO] Booting worker with pid: 2432\n",
      "[2023-02-23 07:30:27 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2429)\n",
      "[2023-02-23 07:30:28 +0100] [2429] [INFO] Worker exiting (pid: 2429)\n",
      "[2023-02-23 07:30:30 +0100] [2465] [INFO] Booting worker with pid: 2465\n",
      "[2023-02-23 12:16:47 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2430)\n",
      "[2023-02-23 12:16:47 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2431)\n",
      "[2023-02-23 12:16:47 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2432)\n",
      "[2023-02-23 12:16:47 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:2465)\n",
      "[2023-02-23 12:16:48 +0100] [2465] [INFO] Worker exiting (pid: 2465)\n",
      "[2023-02-23 12:16:48 +0100] [2431] [INFO] Worker exiting (pid: 2431)\n",
      "[2023-02-23 12:16:48 +0100] [2430] [INFO] Worker exiting (pid: 2430)\n",
      "[2023-02-23 12:16:48 +0100] [2432] [INFO] Worker exiting (pid: 2432)\n",
      "[2023-02-23 12:16:49 +0100] [67691] [WARNING] Worker with pid 2465 was terminated due to signal 9\n",
      "[2023-02-23 12:16:49 +0100] [67691] [WARNING] Worker with pid 2432 was terminated due to signal 9\n",
      "[2023-02-23 12:16:49 +0100] [67691] [WARNING] Worker with pid 2430 was terminated due to signal 9\n",
      "[2023-02-23 12:16:49 +0100] [67691] [WARNING] Worker with pid 2431 was terminated due to signal 9\n",
      "[2023-02-23 12:16:49 +0100] [28576] [INFO] Booting worker with pid: 28576\n",
      "[2023-02-23 12:16:49 +0100] [28578] [INFO] Booting worker with pid: 28578\n",
      "[2023-02-23 12:16:49 +0100] [28579] [INFO] Booting worker with pid: 28579\n",
      "[2023-02-23 12:16:49 +0100] [28580] [INFO] Booting worker with pid: 28580\n",
      "[2023-02-23 12:17:58 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28576)\n",
      "[2023-02-23 12:17:58 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28578)\n",
      "[2023-02-23 12:17:58 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28579)\n",
      "[2023-02-23 12:17:58 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28580)\n",
      "[2023-02-23 12:17:58 +0100] [28576] [INFO] Worker exiting (pid: 28576)\n",
      "[2023-02-23 12:17:58 +0100] [28578] [INFO] Worker exiting (pid: 28578)\n",
      "[2023-02-23 12:17:58 +0100] [28579] [INFO] Worker exiting (pid: 28579)\n",
      "[2023-02-23 12:17:58 +0100] [28580] [INFO] Worker exiting (pid: 28580)\n",
      "[2023-02-23 12:17:58 +0100] [28735] [INFO] Booting worker with pid: 28735\n",
      "[2023-02-23 12:17:58 +0100] [28736] [INFO] Booting worker with pid: 28736\n",
      "[2023-02-23 12:17:58 +0100] [28737] [INFO] Booting worker with pid: 28737\n",
      "[2023-02-23 12:17:58 +0100] [28738] [INFO] Booting worker with pid: 28738\n",
      "[2023-02-23 12:26:20 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28735)\n",
      "[2023-02-23 12:26:20 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28736)\n",
      "[2023-02-23 12:26:20 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28737)\n",
      "[2023-02-23 12:26:20 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28738)\n",
      "[2023-02-23 12:26:20 +0100] [28737] [INFO] Worker exiting (pid: 28737)\n",
      "[2023-02-23 12:26:20 +0100] [28738] [INFO] Worker exiting (pid: 28738)\n",
      "[2023-02-23 12:26:20 +0100] [28736] [INFO] Worker exiting (pid: 28736)\n",
      "[2023-02-23 12:26:20 +0100] [28735] [INFO] Worker exiting (pid: 28735)\n",
      "[2023-02-23 12:26:21 +0100] [28786] [INFO] Booting worker with pid: 28786\n",
      "[2023-02-23 12:26:21 +0100] [67691] [WARNING] Worker with pid 28737 was terminated due to signal 9\n",
      "[2023-02-23 12:26:21 +0100] [28787] [INFO] Booting worker with pid: 28787\n",
      "[2023-02-23 12:26:21 +0100] [28788] [INFO] Booting worker with pid: 28788\n",
      "[2023-02-23 12:26:21 +0100] [28789] [INFO] Booting worker with pid: 28789\n",
      "[2023-02-23 12:51:55 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28786)\n",
      "[2023-02-23 12:51:55 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28787)\n",
      "[2023-02-23 12:51:55 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28788)\n",
      "[2023-02-23 12:51:55 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28789)\n",
      "[2023-02-23 12:51:55 +0100] [28789] [INFO] Worker exiting (pid: 28789)\n",
      "[2023-02-23 12:51:55 +0100] [28786] [INFO] Worker exiting (pid: 28786)\n",
      "[2023-02-23 12:51:55 +0100] [28788] [INFO] Worker exiting (pid: 28788)\n",
      "[2023-02-23 12:51:55 +0100] [28787] [INFO] Worker exiting (pid: 28787)\n",
      "[2023-02-23 12:51:56 +0100] [28875] [INFO] Booting worker with pid: 28875\n",
      "[2023-02-23 12:51:56 +0100] [28878] [INFO] Booting worker with pid: 28878\n",
      "[2023-02-23 12:51:56 +0100] [28880] [INFO] Booting worker with pid: 28880\n",
      "[2023-02-23 12:51:56 +0100] [28881] [INFO] Booting worker with pid: 28881\n",
      "[2023-02-23 13:07:03 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28875)\n",
      "[2023-02-23 13:07:03 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28878)\n",
      "[2023-02-23 13:07:03 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28880)\n",
      "[2023-02-23 13:07:03 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:28881)\n",
      "[2023-02-23 13:07:03 +0100] [28875] [INFO] Worker exiting (pid: 28875)\n",
      "[2023-02-23 13:07:03 +0100] [28878] [INFO] Worker exiting (pid: 28878)\n",
      "[2023-02-23 13:07:03 +0100] [28880] [INFO] Worker exiting (pid: 28880)\n",
      "[2023-02-23 13:07:03 +0100] [28881] [INFO] Worker exiting (pid: 28881)\n",
      "[2023-02-23 13:07:04 +0100] [29105] [INFO] Booting worker with pid: 29105\n",
      "[2023-02-23 13:07:04 +0100] [29106] [INFO] Booting worker with pid: 29106\n",
      "[2023-02-23 13:07:04 +0100] [29107] [INFO] Booting worker with pid: 29107\n",
      "[2023-02-23 13:07:04 +0100] [29108] [INFO] Booting worker with pid: 29108\n",
      "[2023-02-23 13:09:08 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29105)\n",
      "[2023-02-23 13:09:08 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29106)\n",
      "[2023-02-23 13:09:08 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29107)\n",
      "[2023-02-23 13:09:08 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29108)\n",
      "[2023-02-23 13:09:08 +0100] [29105] [INFO] Worker exiting (pid: 29105)\n",
      "[2023-02-23 13:09:08 +0100] [29107] [INFO] Worker exiting (pid: 29107)\n",
      "[2023-02-23 13:09:08 +0100] [29108] [INFO] Worker exiting (pid: 29108)\n",
      "[2023-02-23 13:09:08 +0100] [29106] [INFO] Worker exiting (pid: 29106)\n",
      "[2023-02-23 13:09:09 +0100] [29266] [INFO] Booting worker with pid: 29266\n",
      "[2023-02-23 13:09:09 +0100] [29267] [INFO] Booting worker with pid: 29267\n",
      "[2023-02-23 13:09:09 +0100] [29268] [INFO] Booting worker with pid: 29268\n",
      "[2023-02-23 13:09:09 +0100] [29269] [INFO] Booting worker with pid: 29269\n",
      "[2023-02-23 13:30:38 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29266)\n",
      "[2023-02-23 13:30:38 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29267)\n",
      "[2023-02-23 13:30:38 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29268)\n",
      "[2023-02-23 13:30:38 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:29269)\n",
      "[2023-02-23 13:30:38 +0100] [29268] [INFO] Worker exiting (pid: 29268)\n",
      "[2023-02-23 13:30:38 +0100] [29266] [INFO] Worker exiting (pid: 29266)\n",
      "[2023-02-23 13:30:38 +0100] [29267] [INFO] Worker exiting (pid: 29267)\n",
      "[2023-02-23 13:30:38 +0100] [29269] [INFO] Worker exiting (pid: 29269)\n",
      "[2023-02-23 13:30:39 +0100] [67691] [WARNING] Worker with pid 29268 was terminated due to signal 9\n",
      "[2023-02-23 13:30:39 +0100] [67691] [WARNING] Worker with pid 29267 was terminated due to signal 9\n",
      "[2023-02-23 13:30:39 +0100] [67691] [WARNING] Worker with pid 29266 was terminated due to signal 9\n",
      "[2023-02-23 13:30:39 +0100] [67691] [WARNING] Worker with pid 29269 was terminated due to signal 9\n",
      "[2023-02-23 13:30:39 +0100] [30581] [INFO] Booting worker with pid: 30581\n",
      "[2023-02-23 13:30:39 +0100] [30583] [INFO] Booting worker with pid: 30583\n",
      "[2023-02-23 13:30:39 +0100] [30586] [INFO] Booting worker with pid: 30586\n",
      "[2023-02-23 13:30:39 +0100] [30587] [INFO] Booting worker with pid: 30587\n",
      "[2023-02-23 15:04:31 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:30581)\n",
      "[2023-02-23 15:04:31 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:30583)\n",
      "[2023-02-23 15:04:31 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:30586)\n",
      "[2023-02-23 15:04:31 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:30587)\n",
      "[2023-02-23 15:04:31 +0100] [30586] [INFO] Worker exiting (pid: 30586)\n",
      "[2023-02-23 15:04:31 +0100] [30583] [INFO] Worker exiting (pid: 30583)\n",
      "[2023-02-23 15:04:31 +0100] [30587] [INFO] Worker exiting (pid: 30587)\n",
      "[2023-02-23 15:04:31 +0100] [30581] [INFO] Worker exiting (pid: 30581)\n",
      "[2023-02-23 15:04:32 +0100] [67691] [WARNING] Worker with pid 30583 was terminated due to signal 9\n",
      "[2023-02-23 15:04:32 +0100] [35244] [INFO] Booting worker with pid: 35244\n",
      "[2023-02-23 15:04:32 +0100] [67691] [WARNING] Worker with pid 30586 was terminated due to signal 9\n",
      "[2023-02-23 15:04:32 +0100] [67691] [WARNING] Worker with pid 30587 was terminated due to signal 9\n",
      "[2023-02-23 15:04:32 +0100] [67691] [WARNING] Worker with pid 30581 was terminated due to signal 9\n",
      "[2023-02-23 15:04:32 +0100] [35245] [INFO] Booting worker with pid: 35245\n",
      "[2023-02-23 15:04:32 +0100] [35246] [INFO] Booting worker with pid: 35246\n",
      "[2023-02-23 15:04:32 +0100] [35247] [INFO] Booting worker with pid: 35247\n",
      "[2023-02-23 15:51:11 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:35244)\n",
      "[2023-02-23 15:51:11 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:35245)\n",
      "[2023-02-23 15:51:11 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:35246)\n",
      "[2023-02-23 15:51:11 +0100] [67691] [CRITICAL] WORKER TIMEOUT (pid:35247)\n",
      "[2023-02-23 15:51:11 +0100] [35245] [INFO] Worker exiting (pid: 35245)\n",
      "[2023-02-23 15:51:11 +0100] [35244] [INFO] Worker exiting (pid: 35244)\n",
      "[2023-02-23 15:51:11 +0100] [35247] [INFO] Worker exiting (pid: 35247)\n",
      "[2023-02-23 15:51:11 +0100] [35246] [INFO] Worker exiting (pid: 35246)\n",
      "[2023-02-23 15:51:12 +0100] [67691] [WARNING] Worker with pid 35247 was terminated due to signal 9\n",
      "[2023-02-23 15:51:12 +0100] [67691] [WARNING] Worker with pid 35245 was terminated due to signal 9\n",
      "[2023-02-23 15:51:12 +0100] [67691] [WARNING] Worker with pid 35244 was terminated due to signal 9\n",
      "[2023-02-23 15:51:12 +0100] [67691] [WARNING] Worker with pid 35246 was terminated due to signal 9\n",
      "[2023-02-23 15:51:12 +0100] [37588] [INFO] Booting worker with pid: 37588\n",
      "[2023-02-23 15:51:12 +0100] [37590] [INFO] Booting worker with pid: 37590\n",
      "[2023-02-23 15:51:12 +0100] [37592] [INFO] Booting worker with pid: 37592\n",
      "[2023-02-23 15:51:13 +0100] [37593] [INFO] Booting worker with pid: 37593\n",
      "2023/02/23 16:09:28 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/runs/search [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/server/handlers.py\", line 459, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/server/handlers.py\", line 529, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/server/handlers.py\", line 903, in _search_runs\n",
      "    run_entities = _get_tracking_store().search_runs(\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/store/tracking/abstract_store.py\", line 297, in search_runs\n",
      "    runs, token = self._search_runs(\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py\", line 888, in _search_runs\n",
      "    run_infos = self._list_run_infos(experiment_id, run_view_type)\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py\", line 839, in _list_run_infos\n",
      "    self._check_root_dir()\n",
      "  File \"/Applications/anaconda3/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py\", line 173, in _check_root_dir\n",
      "    raise Exception(\"'%s' does not exist.\" % self.root_directory)\n",
      "Exception: '../../mlrun' does not exist.\n"
     ]
    }
   ],
   "source": [
    "NUM_EPOCHS = 80  # 10\n",
    "f = 0.01\n",
    "batch_size = 2\n",
    "path = \"../../Data/blocksworld\"\n",
    "# path = \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/programming/generateSAT/samples_medium/\"\n",
    "N_STEPS_MOSER = 1000\n",
    "N_RUNS_MOSER = 2\n",
    "SEED = 0\n",
    "network_definition = network_definition_GCN_single_output\n",
    "mode = \"VCG\"\n",
    "\n",
    "MODEL_REGISTRY = Path(\"../../../mlrun\")\n",
    "EXPERIMENT_NAME = \"mlflow-blocksat_interaction_LCG\"\n",
    "# EXPERIMENT_NAME = \"mlflow-random_3SAT-medium-GCN-LCG\"\n",
    "\n",
    "experiment_tracking_train(\n",
    "        MODEL_REGISTRY,\n",
    "        EXPERIMENT_NAME,\n",
    "        batch_size,\n",
    "        f,\n",
    "        NUM_EPOCHS,\n",
    "        N_STEPS_MOSER,\n",
    "        N_RUNS_MOSER,\n",
    "        path,\n",
    "        img_path=\"show\",\n",
    "        model_path=False,\n",
    "        network_definition=network_definition,\n",
    "        mode=mode,\n",
    "    )\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Open MLflow UI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "zsh:1: command not found: npx\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2023-02-21 14:59:10 +0100] [67691] [INFO] Starting gunicorn 20.1.0\n",
      "[2023-02-21 14:59:10 +0100] [67691] [INFO] Listening at: http://0.0.0.0:8013 (67691)\n",
      "[2023-02-21 14:59:10 +0100] [67691] [INFO] Using worker: sync\n",
      "[2023-02-21 14:59:10 +0100] [67692] [INFO] Booting worker with pid: 67692\n",
      "[2023-02-21 14:59:10 +0100] [67693] [INFO] Booting worker with pid: 67693\n",
      "[2023-02-21 14:59:10 +0100] [67694] [INFO] Booting worker with pid: 67694\n",
      "[2023-02-21 14:59:10 +0100] [67695] [INFO] Booting worker with pid: 67695\n"
     ]
    }
   ],
   "source": [
    "# Run MLFlow server and localtunnel\n",
    "print()\n",
    "\n",
    "# get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8010 --backend-store-uri $PWD/experiment_storing/ &\")\n",
    "get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8013 --backend-store-uri '../../../mlrun' &\")\n",
    "!npx localtunnel --port 8013"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "You can open this by typing http://localhost:8013 into your browser\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "zsh:1: command not found: npx\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2023-04-12 13:23:51 +0200] [22634] [INFO] Starting gunicorn 20.1.0\n",
      "[2023-04-12 13:23:51 +0200] [22634] [INFO] Listening at: http://0.0.0.0:8013 (22634)\n",
      "[2023-04-12 13:23:51 +0200] [22634] [INFO] Using worker: sync\n",
      "[2023-04-12 13:23:51 +0200] [22635] [INFO] Booting worker with pid: 22635\n",
      "[2023-04-12 13:23:51 +0200] [22636] [INFO] Booting worker with pid: 22636\n",
      "[2023-04-12 13:23:51 +0200] [22637] [INFO] Booting worker with pid: 22637\n",
      "[2023-04-12 13:23:51 +0200] [22638] [INFO] Booting worker with pid: 22638\n"
     ]
    }
   ],
   "source": [
    "# Run MLFlow server and localtunnel\n",
    "print()\n",
    "\n",
    "# get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8010 --backend-store-uri $PWD/experiment_storing/ &\")\n",
    "get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8013 --backend-store-uri '../../../../mlrun_save' &\")\n",
    "!npx localtunnel --port 8013"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "zsh:1: command not found: npx\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2023-06-06 10:43:40 +0200] [26430] [INFO] Starting gunicorn 20.1.0\n",
      "[2023-06-06 10:43:40 +0200] [26430] [INFO] Listening at: http://0.0.0.0:8014 (26430)\n",
      "[2023-06-06 10:43:40 +0200] [26430] [INFO] Using worker: sync\n",
      "[2023-06-06 10:43:40 +0200] [26432] [INFO] Booting worker with pid: 26432\n",
      "[2023-06-06 10:43:40 +0200] [26435] [INFO] Booting worker with pid: 26435\n",
      "[2023-06-06 10:43:40 +0200] [26436] [INFO] Booting worker with pid: 26436\n",
      "[2023-06-06 10:43:40 +0200] [26437] [INFO] Booting worker with pid: 26437\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "[2023-06-06 13:10:49 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:26432)\n",
      "[2023-06-06 13:10:49 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:26435)\n",
      "[2023-06-06 13:10:49 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:26436)\n",
      "[2023-06-06 13:10:49 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:26437)\n",
      "[2023-06-06 13:10:49 +0200] [26432] [INFO] Worker exiting (pid: 26432)\n",
      "[2023-06-06 13:10:49 +0200] [26435] [INFO] Worker exiting (pid: 26435)\n",
      "[2023-06-06 13:10:49 +0200] [26436] [INFO] Worker exiting (pid: 26436)\n",
      "[2023-06-06 13:10:49 +0200] [26437] [INFO] Worker exiting (pid: 26437)\n",
      "[2023-06-06 13:10:50 +0200] [26430] [WARNING] Worker with pid 26437 was terminated due to signal 9\n",
      "[2023-06-06 13:10:50 +0200] [26430] [WARNING] Worker with pid 26435 was terminated due to signal 9\n",
      "[2023-06-06 13:10:50 +0200] [26430] [WARNING] Worker with pid 26432 was terminated due to signal 9\n",
      "[2023-06-06 13:10:50 +0200] [26430] [WARNING] Worker with pid 26436 was terminated due to signal 9\n",
      "[2023-06-06 13:10:50 +0200] [32597] [INFO] Booting worker with pid: 32597\n",
      "[2023-06-06 13:10:50 +0200] [32598] [INFO] Booting worker with pid: 32598\n",
      "[2023-06-06 13:10:50 +0200] [32600] [INFO] Booting worker with pid: 32600\n",
      "[2023-06-06 13:10:50 +0200] [32601] [INFO] Booting worker with pid: 32601\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '603983687658095993'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/603983687658095993/meta.yaml' does not exist.\n",
      "WARNING:root:Malformed experiment '634047769586963630'. Detailed error Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 290, in search_experiments\n",
      "    exp = self._get_experiment(exp_id, view_type)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 383, in _get_experiment\n",
      "    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1096, in _read_yaml\n",
      "    return _read_helper(root, file_name, attempts_remaining=retries)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/store/tracking/file_store.py\", line 1089, in _read_helper\n",
      "    result = read_yaml(root, file_name)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/.venv/lib/python3.11/site-packages/mlflow/utils/file_utils.py\", line 215, in read_yaml\n",
      "    raise MissingConfigException(\"Yaml file '%s' does not exist.\" % file_path)\n",
      "mlflow.exceptions.MissingConfigException: Yaml file '/Users/p403830/Downloads/aws_mlrun/634047769586963630/meta.yaml' does not exist.\n",
      "[2023-06-06 15:59:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:32597)\n",
      "[2023-06-06 15:59:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:32598)\n",
      "[2023-06-06 15:59:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:32600)\n",
      "[2023-06-06 15:59:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:32601)\n",
      "[2023-06-06 15:59:19 +0200] [32600] [INFO] Worker exiting (pid: 32600)\n",
      "[2023-06-06 15:59:19 +0200] [32597] [INFO] Worker exiting (pid: 32597)\n",
      "[2023-06-06 15:59:19 +0200] [32601] [INFO] Worker exiting (pid: 32601)\n",
      "[2023-06-06 15:59:19 +0200] [32598] [INFO] Worker exiting (pid: 32598)\n",
      "[2023-06-06 15:59:20 +0200] [26430] [WARNING] Worker with pid 32598 was terminated due to signal 9\n",
      "[2023-06-06 15:59:20 +0200] [26430] [WARNING] Worker with pid 32601 was terminated due to signal 9\n",
      "[2023-06-06 15:59:20 +0200] [26430] [WARNING] Worker with pid 32600 was terminated due to signal 9\n",
      "[2023-06-06 15:59:20 +0200] [26430] [WARNING] Worker with pid 32597 was terminated due to signal 9\n",
      "[2023-06-06 15:59:20 +0200] [40410] [INFO] Booting worker with pid: 40410\n",
      "[2023-06-06 15:59:20 +0200] [40411] [INFO] Booting worker with pid: 40411\n",
      "[2023-06-06 15:59:20 +0200] [40412] [INFO] Booting worker with pid: 40412\n",
      "[2023-06-06 15:59:20 +0200] [40413] [INFO] Booting worker with pid: 40413\n",
      "[2023-06-06 16:53:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:40410)\n",
      "[2023-06-06 16:53:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:40411)\n",
      "[2023-06-06 16:53:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:40412)\n",
      "[2023-06-06 16:53:19 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:40413)\n",
      "[2023-06-06 16:53:20 +0200] [40413] [INFO] Worker exiting (pid: 40413)\n",
      "[2023-06-06 16:53:20 +0200] [40412] [INFO] Worker exiting (pid: 40412)\n",
      "[2023-06-06 16:53:20 +0200] [40411] [INFO] Worker exiting (pid: 40411)\n",
      "[2023-06-06 16:53:20 +0200] [40410] [INFO] Worker exiting (pid: 40410)\n",
      "[2023-06-06 16:53:20 +0200] [26430] [WARNING] Worker with pid 40412 was terminated due to signal 9\n",
      "[2023-06-06 16:53:20 +0200] [26430] [WARNING] Worker with pid 40410 was terminated due to signal 9\n",
      "[2023-06-06 16:53:20 +0200] [26430] [WARNING] Worker with pid 40413 was terminated due to signal 9\n",
      "[2023-06-06 16:53:20 +0200] [26430] [WARNING] Worker with pid 40411 was terminated due to signal 9\n",
      "[2023-06-06 16:53:21 +0200] [42164] [INFO] Booting worker with pid: 42164\n",
      "[2023-06-06 16:53:21 +0200] [42165] [INFO] Booting worker with pid: 42165\n",
      "[2023-06-06 16:53:21 +0200] [42166] [INFO] Booting worker with pid: 42166\n",
      "[2023-06-06 16:53:21 +0200] [42167] [INFO] Booting worker with pid: 42167\n",
      "[2023-06-06 16:56:18 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:42164)\n",
      "[2023-06-06 16:56:18 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:42165)\n",
      "[2023-06-06 16:56:18 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:42166)\n",
      "[2023-06-06 16:56:18 +0200] [26430] [CRITICAL] WORKER TIMEOUT (pid:42167)\n",
      "[2023-06-06 16:56:19 +0200] [42165] [INFO] Worker exiting (pid: 42165)\n",
      "[2023-06-06 16:56:19 +0200] [42167] [INFO] Worker exiting (pid: 42167)\n",
      "[2023-06-06 16:56:19 +0200] [42166] [INFO] Worker exiting (pid: 42166)\n",
      "[2023-06-06 16:56:19 +0200] [42164] [INFO] Worker exiting (pid: 42164)\n",
      "[2023-06-06 16:56:19 +0200] [42205] [INFO] Booting worker with pid: 42205\n",
      "[2023-06-06 16:56:20 +0200] [42206] [INFO] Booting worker with pid: 42206\n",
      "[2023-06-06 16:56:20 +0200] [42207] [INFO] Booting worker with pid: 42207\n",
      "[2023-06-06 16:56:20 +0200] [42208] [INFO] Booting worker with pid: 42208\n"
     ]
    }
   ],
   "source": [
    "# Run MLFlow server and localtunnel\n",
    "print()\n",
    "\n",
    "# get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8010 --backend-store-uri $PWD/experiment_storing/ &\")\n",
    "get_ipython().system_raw(\"mlflow server -h 0.0.0.0 -p 8014 --backend-store-uri '/Users/p403830/Downloads/aws_mlrun' &\")\n",
    "!npx localtunnel --port 8014\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "cd78fef2128015050713e82ca51c6520b11aee7c9ee8df750520bbbc7384cbaa"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
